config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "pages/dashboard"
  resources :categories
  resources :coats do
    resources :bookings, only: [:new, :create, :show]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :coat
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :coats
end

app/models/coat.rb
class Coat < ApplicationRecord
  belongs_to :user
  belongs_to :category
  mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_user, only: [:index, :show]

  def index
    @categories = []
    @bookings.each do |booking|
      @categories << booking.coat.category
    end
    @categories = @categories.uniq
  end

  def new
    @booking = Booking.new
    @coat = Coat.find(params[:coat_id])
  end

  def create
    @coat = Coat.find(params[:coat_id])
    @booking = Booking.create(booking_params)
    @booking.coat = @coat
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def show
  end

  private

  def set_user
    @user  = current_user
    @bookings = Booking.where(user: @user)
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :coat_id, :user_id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @coats = @category.coats
    # Add search logic
    if !params[:name].blank?
      @coats = @coats.where("name LIKE ?", "%#{params[:name].capitalize}%")
    end
    if !params[:size].blank?
      @coats = @coats.where(size: params[:size])
    end
    if !params[:price].blank?
      @coats = @coats.where("price <= ?", params[:price])
    end
  end

  def index
    @categories = Category.all
  end
end

app/controllers/coats_controller.rb
class CoatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @coats = Coat.all
    if !params[:name].blank?
      @coats = @coats.where("name LIKE ?", "%#{params[:name].downcase}%")
    end
    if !params[:size].blank?
      @coats = @coats.where(size: params[:size])
    end
    if !params[:price].blank?
      @coats = @coats.where("price <= ?", params[:price])
    end
  end

  def show

    @coat = Coat.find(params[:id])
    @booking = Booking.new

    @markers = [
      {
        lat: @coat.user.latitude,
        lng: @coat.user.longitude
      }]
  end

  def new
    @coat = Coat.new
  end

  def create
    @coat = Coat.new(coat_params)
    @coat.user = current_user
    if @coat.save
      redirect_to coat_path(@coat)
    else
      render 'new'
    end
  end

  private

  def coat_params
    params.require(:coat).permit(:name, :price, :size, :category_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_dashboard.html.erb
<div class="container dash-container">
  <div class="col-xs-12 col-sm-10-col-sm-offset-1">
    <!-- Add account -->
    <!-- Show linked accounts -->

    <div class="linked-accounts" >
      <% if !@bookings.blank? %>
        <% @categories.each do |category| %>
          <%= link_to category do %>
            <div class="base-card bank-card" style="background-image: url(<%= category.photo %>);">
              <h3><strong><%= category.name %></strong></h3>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%= link_to categories_path, class: "no-hover-link" do %>
        <div class="base-card bank-card" id="add-card">
          <i class="fas fa-plus-circle"></i>
        </div>
      <% end %>
    </div>
    <!-- Check if any bookings -->
    <% if @bookings.blank? %>
      <div class="no-booking">
        <h3><%= "You have no bookings yet!" %></h3>
      </div>
    <% end %>
    <!-- Start of a dashboard card -->
    <div id="sub-cards">
      <% @bookings.each do |booking| %>
        <div class="base-card dashboard-card">
          <div class="sub-logo" style="background-image: url(<%= booking.coat.photo %>);"></div>
          <div class="dash-card-item">
            <i class="fas fa-euro-sign"></i>
            <h3>EUR <%= booking.coat.price %> /w</h3>
          </div>
          <div class="dash-card-item-cat hidden"><%= booking.coat.category.name %> </div>
          <div class="dash-detail-sum">
            <div class="d-flex align-items-center">
              <i class="fas fa-info-circle"></i>
            </div>
            <div class="d-flex flex-column">
              <h4 style="font-weight: lighter;">Title: <%= booking.coat.name %> </h4>
              <h4 style="font-weight: lighter;">Category: <%= booking.coat.category.name %> </h4>
            </div>
          </div>
          <div class="dash-card-item">
            <i class="far fa-calendar-alt"></i><h3> <%= booking.start_date %> </h3>
          </div>
          <div class="dash-button">
            <%= simple_form_for "#" do |f| %>
              <%= f.button :submit, "Reminder", class: "form-button" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<%= render "booking_dashboard" %>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>


<div class="col-xs-12 col-sm-4">
  <%= render "forms/booking_form" %>
</div>

app/views/bookings/show.html.erb
<%= render "booking_dashboard" %>

app/views/categories/index.html.erb
<div class="dash-container">
  <div class="category-banner" style="background-image: url(https://res.cloudinary.com/dzcwxfufs/image/upload/v1533737761/Screen-Shot-2017-04-15-at-7.59.03-PM.png);">
    <div class="category-banner-content">
      <h1>Coat Yourself</h1>
    </div>
  </div>

  <% @categories.each do |category| %>
    <%= link_to category_path(category) do %>
    <div class="category-card" style="background-image: url( <%=category.photo %>);">
      <div class="category-card-category">Category</div>
      <div class="category-card-description">
        <h2><%= category.name%></h2>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="big-container">
    <div class="card-show-cat" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @category.photo %>);">
      <div class="card-description-cat-show">
        <h2><%=@category.name%></h2>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <%= render "forms/category_search" %>
        </div>
        <% @coats.each do |coat| %>
          <div class="col-xs-12 col-sm-6 col-md-3">
            <%= link_to coat_path(coat) do %>
              <div class="card-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= coat.photo %>);">
                <div class="card-category-name-show"><%= coat.name %></div>
                <div class="card-category-cat-show"><%= coat.size %></div>
                <div class="card-description-cat-show"><%= "#{coat.price} €"   %></div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/coats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <%= render "forms/category_search" %>
    </div>
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <h3> Test Result </h3>
      <% @coats.each do |coat| %>
        <%= coat.name %>
      <% end %>
    </div>
  </div>
</div>

app/views/coats/new.html.erb
<div class="form-container form-margin-top">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-card">
        <h2>Add a new Coat</h2>
        <%= simple_form_for @coat do |f| %>
        <%= f.input :name %>
        <%= f.input :category_id, label: "Category", collection: Category.all %>
        <%= f.input :price %>
        <%= f.input :size, collection: ["Small", "Medium", "Large"] %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: "form-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/coats/show.html.erb
<div class="container">

  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
    <div class="banner-content">
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">

      <div class="form-group search-form">
        <h3> Your coat details </h3>
        <div class="features">
          <p style="color:black;"><strong>COAT </strong><%=@coat.name %></a></p>
          <p style="color:black;"><strong>SIZE </strong><%=@coat.size %></a></p>
          <p style="color:black;"><strong>PRICE </strong><%=@coat.price %>EUR</p>
          <div class="card-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @coat.photo %>);">
          </div>
        </div>
      </div>
    </div>
      <div class="col-xs-12 col-sm-6">
        <%= render "forms/booking_form" %>
    </div>
  </div>
  <div
    class="map-img"
    style="background-image: url('https://res.cloudinary.com/dzcwxfufs/image/upload/v1533913574/samples/map.png')"
    data-markers="<%= @markers.to_json %>">
  </div>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
</div>

app/views/forms/_booking_form.html.erb
  <div class="form-group search-form">
    <h3> Book This Coat! </h3>
    <%= simple_form_for [@coat, @booking] do |f| %>
      <div class="col-xs-12 col-sm-12">
       <%= f.input :start_date %>
      </div>
      <div class="col-xs-12 col-sm-12">
        <%= f.input :end_date %>
      </div>
      <div class="col-xs-12 col-sm-12">
        <%= f.submit "submit request", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

app/views/forms/_category_search.html.erb
<form role="form" class="form-horizontal">
  <div class="form-group search-form">
    <h3> Find Your Coat! </h3>
    <%= form_tag(coats_path, :method => "get", class: "form-group search-field") do %>
      <div class="col-xs-12 col-sm-12">
        <%= label_tag :name, 'Key words' %>
        <%= text_field_tag :name, params[:search], placeholder: "key words", class: "form-control search-field" %>
      </div>
      <div class="col-xs-12 col-sm-12">
        <%= label_tag :size, 'Choose your size' %>
        <%= select_tag :size, options_for_select([["any size", ""], ["small", "small"], ["medium", "Medium"], ["large", "Large"]], params[:size]), class: "form-control search-field" %>
      </div>
      <div class="col-xs-12 col-sm-12">
        <%= label_tag :size, 'Max price per week' %>
        <%= number_field_tag :price, params[:search], placeholder: "any price",class: "form-control search-field"  %>
      </div>
      <div class="col-xs-12 col-sm-12">
        <%= submit_tag "Search", class: "btn btn-primary search-field" %>
      </div>
    <% end %>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Coat Yourself</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

  </head>
  <body>
    <% if current_page?(root_path) %>
      <%= render 'shared/navbar-transparent' %>
    <% else %>
      <%= render 'shared/navbar-blue' %>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-10-col-sm-offset-1">
    <div class="linked-accounts" >
      <div class="base-card bank-card" style="background-image: url( https://res.cloudinary.com/dzcwxfufs/image/upload/v1533655051/2ad92f03deeca4aa5e8b2fb27e8de16b.jpg);">
        Bank Card 1
      </div>
      <div class="base-card bank-card " style="background-image: url(https://res.cloudinary.com/dzcwxfufs/image/upload/v1533655763/800px_COLOURBOX13351686.jpg);"></div>
      <div class="base-card bank-card">
        <i class="fas fa-plus-circle"></i>
      </div>
    </div>
    <!-- Start of a dashboard card -->
    <div class="base-card dashboard-card">
      <div class="sub-logo" style="background-image: url('http://cdn1.bigcommerce.com/n-ou1isn/qaxbjhup/products/670/images/4728/mens-santa-equality-black-santa-christmas-suit-coat-2__43510.1476363990.500.900.jpg?c=2');"></div>
      <div class="dash-card-item">
        <i class="fas fa-euro-sign"></i>
        <h3>EUR 10 /w</h3>
      </div>
      <div class="dash-detail-sum">
        <i class="fas fa-info-circle"></i>
        <h3>$100 over last 12 months</h3>
      </div>
      <div class="dash-card-item">
        <i class="far fa-calendar-alt"></i><h3>18 Sep 2018</h3>
      </div>
      <div class="dash-button">
        <%= simple_form_for "#" do |f| %>
          <%= f.button :submit, "Reminder", class: "form-button" %>
        <% end %>
      </div>
    </div>
    <!-- Start of a dashboard card -->
    <div class="base-card dashboard-card">
      <div class="sub-logo" style="background-image: url('https://inhabitat.com/ecouterre/wp-content/blogs.dir/26/files/2013/12/fur-coat-1.jpg');"></div>
      <div class="dash-card-item">
        <i class="fas fa-euro-sign"></i>
        <h3>EUR 10 /w</h3>
      </div>
      <div class="dash-detail-sum">
        <i class="fas fa-info-circle"></i>
        <h3>$100 over last 12 months</h3>
      </div>
      <div class="dash-card-item">
        <i class="far fa-calendar-alt"></i><h3>18 Sep 2018</h3>
      </div>
      <div class="dash-button">
        <%= simple_form_for "#" do |f| %>
          <%= f.button :submit, "Reminder", class: "form-button" %>
        <% end %>
      </div>
    </div>
    <!-- Start of a dashboard card -->
    <div class="base-card dashboard-card">
      <div class="sub-logo" style="background-image: url('https://www.easterncostume.com/files/MODUSA003/fullsize/5.jpg');"></div>
      <div class="dash-card-item">
        <i class="fas fa-euro-sign"></i>
        <h3>EUR 10 /w</h3>
      </div>
      <div class="dash-detail-sum">
        <i class="fas fa-info-circle"></i>
        <h3>$100 over last 12 months</h3>
      </div>
      <div class="dash-card-item">
        <i class="far fa-calendar-alt"></i><h3>18 Sep 2018</h3>
      </div>
      <div class="dash-button">
        <%= simple_form_for "#" do |f| %>
          <%= f.button :submit, "Reminder", class: "form-button" %>
        <% end %>
      </div>
    </div>
    <!-- Start of a dashboard card -->
    <div class="base-card dashboard-card">
      <div class="sub-logo" style="background-image: url('https://www.easterncostume.com/files/MODUSA003/fullsize/5.jpg');"></div>
      <div class="dash-card-item">
        <i class="fas fa-euro-sign"></i>
        <h3>EUR <%= @coat.price %> /w</h3>
      </div>
      <div class="dash-detail-sum">
        <i class="fas fa-info-circle"></i>
        <h3>The owner is <%= @coat.user.name %></h3>
      </div>
      <div class="dash-card-item">
        <i class="far fa-calendar-alt"></i><h3>@booking.start_date</h3>
      </div>
      <div class="dash-button">
        <%= simple_form_for "#" do |f| %>
          <%= f.button :submit, "Reminder", class: "form-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="home-banner">
  <div id="home-wrapper" class="col-xs-12 col-sm-6 col-sm-offset-1">
    <div id="home-banner-content">
      <h1>Coat Yourself</h1>
      <p>Coat it like it's hot!</p>
      <div class="home-center-button">
        <%= link_to "Get Coated", categories_path , class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<div class="scroll">
  <a href="#second-banner"><i class="fas fa-chevron-down"></i></a>
</div>
<div id="second-banner">
  <div class="row">
    <div class="col-xs-6">
      <div id="second-banner-content">
        <h2>Best freaking coats</h2>
        <br>
        <h2>Cheapest freaking coats</h2>
        <br>
        <h2>Coat to GOAT</h2>
      </div>
    </div>
    <div class="col-xs-6">
      <div id="second-banner-content">
      <%= image_tag 'https://www.orangemayonnaise.com/image/shrink/19468/960/720/bengh-per-principesse-fun-fur-coat-bengh-per-principesse-fun-fur-coat.png' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class= "footer-groups">
    <div class="footer-social-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-main-links">
      <a href="#">About</i></a>
      <a href="#">Security</i></a>
      <a href="#">Press Releases</i></a>
      <a href="#">Contact</i></a>
      <a href="#">FAQ</i></a>
    </div>
    <div class="footer-copyright">
      ⒸCoatYourself
    </div>
  </div>
</div>

app/views/shared/_navbar-blue.html.erb
<div class="navbar-wagon navbar-wagon-solid">
  <!-- Logo -->
  <div class="coat-logo">
    <%= link_to root_path do %>
      <i class="fas fa-user-secret"></i>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "jerome.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_coat_path do %>
                <i class="fas fa-plus"></i>  <%= t(".settings", default: "Add new coat") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to('Logout', destroy_user_session_path,  :method=>'delete')  %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Links -->
    <%= link_to "Log In", user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Join", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-join" %>
    </div>
  <% end %>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Sign Out</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar-transparent.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <div class="coat-logo">
    <%= link_to root_path do %>
      <i class="fas fa-user-secret"></i>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "jerome.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_coat_path do %>
                <i class="fas fa-plus"></i>  <%= t(".settings", default: "Add new coat") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to('Logout', destroy_user_session_path,  :method=>'delete')  %>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Links -->
    <%= link_to "Log In", user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Join", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-join" %>
    </div>
  <% end %>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Sign Out</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar-when-signed-in.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= link_to "Ledja", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
<!-- add link to logo check original code-->
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign-out", default: "Sign Out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Sign Out</a></li>
      </ul>
    </div>
  </div>
</div>